#How many rotations to make a full circle in Coarse adjustment mode
coarse: 12

#How many rotations to make a full circle in Fine adjustment mode
fine: 120

#Name of the language file you wish to use
lang: en_US.yml

#If false plugin notifications will be sent to the chat box. If true messages will be sent to the action bar.
sendMessagesToActionBar: true

#Don't set to true unless you want players to see random messages or other undesirable behavior
debug: false